name: Build Debug APK

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@main

      - name: Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Cache Gradle Packages
        uses: actions/cache@v6
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run Tests
        run: nix develop -c ./gradlew test

      - name: Build Debug APK
        run: nix develop -c ./gradlew assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v7
        with:
          path: app/build/outputs/apk/debug/app-debug.apk
          archive: false
